### ISSUE TITLE
Is this being actively maintained?

### ISSUE THREAD

**Issue by eskhool** [greyside/django-config-gen#9]
Hi,
 Are you able to maintain this django app? Asking because a PR we had sent over a year ago is still open? 

If not can somebody update your homepage to indicate that the brillgen fork is actively being maintained and can support users? We are happy to continue as we are still using this package.

Thanks

**Comment by SeanHayes** [comment]
Sure, could you get them to comment here to confirm they'd like to be the new canonical version?

**Comment by eskhool** [comment]
Hi @SeanHayes, I speak for the organization and can confirm that we can continue to support this app. If you can put a redirect on the comments page to 
[brillgen/django-config-gen](https://github.com/brillgen/django-config-gen), we can update our page to reflect the same.
It's not like the app is breaking the internet but hey, we found it useful and exactly what we were looking for.

**Comment by SeanHayes** [comment]
I'm not sure what you mean by redirect, but I just updated the description. Let me know your PyPi username so I can add you as a collaborator.

**Comment by eskhool** [comment]
Yeah, an updated description is what I meant by a (written) redirect. Please add 'brillgen' as the PyPi username which we will use to publish updates.

Thanks. Looking forward to getting and supporting some community interest.

**Comment by eskhool** [comment]
I just saw the updated description. Although its great that you've listed the maintenance info up top but some like me might just be scrolling down to quickly read the features/installation etc. You might want to be put the same link below as well. 

I will get the info page updated with some changes and make a release soon.

**Comment by SeanHayes** [comment]
Done.
